homeassistant:
  # Name of the location where Home Assistant is running
  name: Beach House
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York 
  # Customization file
#  auth_providers:
#   - type: homeassistant
#   - type: legacy_api_password
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/home/homeassistant/.homeassistant/scripts/cameraimages'
    - '/tmp'
auth:
#logger:
#  default: warning
#  logs:
#   homeassistant.components.light.hue: debug
 
google:
  client_id: !secret google_calendar_id
  client_secret: !secret google_calendar_secret

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

timer:
  guests_just_arrived:
    duration: '00:07:00'
  paul_just_arrived:
    duration: '00:07:00'
  tracy_just_arrived:
    duration: '00:07:00'
  frog_tv_reset:
    duration: '00:05:00'
  camera_action:
    duration: '00:00:30'

# Zigbee
zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

# Zwave
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
  autoheal: false
  polling_interval: 30000
  device_config:
    light.bedroom_ceiling_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.frog_ceiling_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.hallway_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.frog_fan_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.kitchen_counter_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.kitchen_island_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.living_room_ceiling_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.living_room_fan_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    light.guest_bedroom_light:
      polling_intensity: 1
      refresh_value: True
      delay: 3
    switch.fireplace:
      polling_intensity: 1
      refresh_value: True
      delay: 2

cover:
  platform: zwave

# Ecobee Components    
ecobee:
  api_key: !secret ecobee_api_key
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret
  
homekit:
  filter:
    include_entities:
      - input_boolean.paul_present
      - input_boolean.tracy_present


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_certificate_key_path
  base_url: !secret base_ha_url

duckdns:
  domain: !secret ha_domain_name
  access_token: !secret duckdns_access_token

emulated_hue:
  host_ip: 192.168.1.15
  expose_by_default: false

# Discover some devices automatically
#discovery:
#  ignore:
#    - songpal
#    - apple_tv

# Record events
recorder:
  purge_interval: 1
  purge_keep_days: 5
  
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
  - platform: voicerss
    api_key: 0baf593ad6bf4792afe6c258b4494ce7
    codec: mp3
    format: '44khz_16bit_stereo'

# iOS Additions
ios:
  push:
    categories:
      - name: Garage Alert
        identifier: 'garage_alert'
        actions:
          - identifier: 'CANCEL_GARAGE_ALERT'
            title: 'Cancel Alert'
          - identifier: 'CLOSE_GARAGE'
            title: 'Close Garage'
      - name: Shopping Alert
        identifier: 'shopping_alert'
        actions:
          - identifier: 'CANCEL_SHOPPING_ALERT'
            title: 'No'
          - identifier: 'OPEN_GARAGE_WHEN_I_GET_HOME'
            title: 'Yes'

asuswrt:
  #- platform: asuswrt
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_password
    protocol: ssh
#    port: 23

# Device Trackers
device_tracker:
  - platform: google_maps
    username: !secret notificationemail
    password: !secret gmailpassword
    max_gps_accuracy: 150
#  - platform: asuswrt
#    host: !secret router_ip
#    username: !secret router_user
#    password: !secret router_password
#    protocol: ssh
#    interval_seconds: 15
#    consider_home: 30
#    track_new_devices: yes
  - platform: life360
    username: !secret life360_user
    password: !secret life360_password
    max_gps_accuracy: 150
#    show_as_state: places, moving
    interval_seconds: 12
    driving_speed: 12
    max_update_wait:
      minutes: 30
  - platform: composite
    name: Paul_All
    entity_id:
      - device_tracker.paul
#      - device_tracker.pauls_iphone
      - device_tracker.google_maps_118013912887885302155
  - platform: composite
    name: Tracy_All
    entity_id:
      - device_tracker.tracy
#      - device_tracker.tracys_iphone
      - device_tracker.google_maps_116112519745623760034


ifttt:
  key: !secret ifttt_key 

input_number:
  commute_start_time:
    name: Commute Start Time
    min: 0
    max: 100000000000
  speech_volume:
    name: Speech Volume
    icon: mdi:message-processing
    min: 1
    max: 20
    step: 1

python_script:

ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

switch:
  - platform: command_line
    switches:
      last_echo_used:
        command_on: "/home/homeassistant/.homeassistant/alexa_remote_control.sh -lastalexa"
        command_off: ""

  - platform: wake_on_lan
    name: "Plex Server"
    host: "192.168.1.11"
    mac_address: "00-50-B6-21-0E-11"

wake_on_lan:

api:

light:
  - platform: template
    lights:
      alexa_virtual:
        friendly_name: "Alexa Dummy Light"
        turn_on:
        turn_off:
        set_level:
  - platform: switch
    name: Sconce Light
    entity_id: switch.sconce_light
  - platform: switch
    name: Stairwell Lighgt
    entity_id: switch.stairwell_light
  - platform: switch
    name: Christmas Tree
    entity_id: switch.living_room_plug_two

#shell_command:
#  snapshot_frontdoor_gif: /home/homeassistant/.homeassistant/www/tmp/gif.sh
shell_command:
  delete_snapshots: 'rm -f /tmp/*.jpg'
  alexa_vol: '/home/homeassistant/.homeassistant/alexa_remote_control.sh -d "{{ device }}" -e vol:{{ volume }} '
  alexa_routine: '/home/homeassistant/.homeassistant/alexa_remote_control.sh -d "{{ device }}" -e automation:"{{ routine }}" '

remote:
  - platform: harmony
    host: 192.168.1.51
    name: Living Room Harmony Hub
  - platform: harmony
    host: 192.168.1.50
    name: Theater Room Harmony Hub 

emulated_roku:
#  SN - sSMJFc3BXnTfjPAPHiY5gb 
  host_ip: 192.168.1.15 # should be set to Home Assistant's address
  upnp_bind_multicast: True # optional, defaults to True
  listen_ports:
    - 8060

media_player:
#  - platform: alexa
#    email: !secret amazon_id
#    password: !secret amazon_password
#    url: amazon.com
  - platform: vizio
    host: 192.168.1.82
    access_token: Z6xoq7pviz
    name: Theater Room TV Control
  - platform: vizio
    host: 192.168.1.84
    access_token: Zbo7pxfs55
    name: Bedroom TV Control
  - platform: braviatv_psk
    name: Living Room TV
    host: 192.168.1.80
    psk: 1234
    mac: 04:5D:4B:AA:70:89
    amp: True
    android: True
    
# View all events in a logbook
logbook: !include logbook.yaml
#cloud: !include cloud.yaml
alexa: !include alexa.yaml
notify: !include notify.yaml
zone: !include zones.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
input_select: !include input_selects.yaml
input_text: !include input_texts.yaml
input_datetime: !include input_datetimes.yaml
input_boolean: !include input_booleans.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
alert: !include alerts.yaml
history: !include history.yaml
camera: !include cameras.yaml
scene: !include scenes.yaml